/**
 * Mock data for demo mode - used for screenshots and previews
 * Enable demo mode by adding ?demo=true to any page URL
 */

import type { Room, Participant, Submission, GameSettings, Track } from '@/types/database'

export const DEMO_GAME_SETTINGS: GameSettings = {
  songsRequired: 5,
  christmasSongsRequired: 2,
  recentSongsRequired: 1,
  chameleonMode: true,
  guessTimerSeconds: 30,
  previewLengthSeconds: 30,
  revealAfterEachRound: true,
  allowDuplicateSongs: false,
  lobbyMusic: true,
  triviaEnabled: true,
  triviaQuestionCount: 10,
  snowEffect: true,
  themeColor: 'green',
}

export const DEMO_ROOM: Room = {
  id: 'demo-room-id',
  room_code: 'JINGLE',
  host_id: 'demo-user-1',
  name: 'Christmas Party 2024',
  status: 'LOBBY',
  current_round: 0,
  settings: DEMO_GAME_SETTINGS,
  playlist_summary: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const DEMO_PARTICIPANTS: Participant[] = [
  {
    id: 'demo-participant-1',
    room_id: 'demo-room-id',
    user_id: 'demo-user-1',
    spotify_id: 'spotify-1',
    display_name: 'Sarah',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah&backgroundColor=b6e3f4',
    score: 450,
    is_host: true,
    has_submitted: true,
    created_at: new Date().toISOString(),
    ai_summary: 'A festive soul who loves classic Christmas crooners and modern holiday pop. Expect Mariah and Michael Bublé!',
    mood_tag: 'Cosy Crooner',
  },
  {
    id: 'demo-participant-2',
    room_id: 'demo-room-id',
    user_id: 'demo-user-2',
    spotify_id: 'spotify-2',
    display_name: 'James',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James&backgroundColor=c0aede',
    score: 380,
    is_host: false,
    has_submitted: true,
    created_at: new Date().toISOString(),
    ai_summary: 'Rock and indie vibes with a festive twist. Thinks The Pogues is peak Christmas music.',
    mood_tag: 'Rebel Elf',
  },
  {
    id: 'demo-participant-3',
    room_id: 'demo-room-id',
    user_id: 'demo-user-3',
    spotify_id: 'spotify-3',
    display_name: 'Emma',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma&backgroundColor=ffd5dc',
    score: 520,
    is_host: false,
    has_submitted: true,
    created_at: new Date().toISOString(),
    ai_summary: 'Pop princess with impeccable taste. Her playlist is basically the John Lewis advert soundtrack.',
    mood_tag: 'Sparkle Queen',
  },
  {
    id: 'demo-participant-4',
    room_id: 'demo-room-id',
    user_id: 'demo-user-4',
    spotify_id: 'spotify-4',
    display_name: 'Tom',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tom&backgroundColor=d1f4d1',
    score: 290,
    is_host: false,
    has_submitted: false,
    created_at: new Date().toISOString(),
    ai_summary: null,
    mood_tag: null,
  },
]

export const DEMO_SUBMISSIONS: Submission[] = [
  // Sarah's submissions
  {
    id: 'sub-1',
    participant_id: 'demo-participant-1',
    track_id: 'track-1',
    track_name: 'All I Want for Christmas Is You',
    artist_name: 'Mariah Carey',
    album_art_url: 'https://i.scdn.co/image/ab67616d0000b273073c569fdb28a8ce4cba66b2',
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    submission_order: 1,
    played: true,
    created_at: new Date().toISOString(),
    album_name: 'Merry Christmas',
    release_year: 1994,
    duration_ms: 241000,
    popularity: 85,
    is_chameleon: false,
  },
  {
    id: 'sub-2',
    participant_id: 'demo-participant-1',
    track_id: 'track-2',
    track_name: "It's Beginning to Look a Lot Like Christmas",
    artist_name: 'Michael Bublé',
    album_art_url: 'https://i.scdn.co/image/ab67616d0000b2736a0a3d5b1e58cce1bfa5d53a',
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    submission_order: 2,
    played: false,
    created_at: new Date().toISOString(),
    album_name: 'Christmas',
    release_year: 2011,
    duration_ms: 210000,
    popularity: 78,
    is_chameleon: false,
  },
  // James's submissions
  {
    id: 'sub-3',
    participant_id: 'demo-participant-2',
    track_id: 'track-3',
    track_name: 'Fairytale of New York',
    artist_name: 'The Pogues',
    album_art_url: 'https://i.scdn.co/image/ab67616d0000b273e17011a1382bfe7e1d3b9286',
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    submission_order: 1,
    played: true,
    created_at: new Date().toISOString(),
    album_name: 'If I Should Fall from Grace with God',
    release_year: 1987,
    duration_ms: 271000,
    popularity: 82,
    is_chameleon: false,
  },
  {
    id: 'sub-4',
    participant_id: 'demo-participant-2',
    track_id: 'track-4',
    track_name: 'Merry Xmas Everybody',
    artist_name: 'Slade',
    album_art_url: 'https://i.scdn.co/image/ab67616d0000b27376dbef01e8c15dc2eb5e0d62',
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    submission_order: 2,
    played: false,
    created_at: new Date().toISOString(),
    album_name: 'Old New Borrowed and Blue',
    release_year: 1973,
    duration_ms: 232000,
    popularity: 75,
    is_chameleon: true,
  },
  // Emma's submissions
  {
    id: 'sub-5',
    participant_id: 'demo-participant-3',
    track_id: 'track-5',
    track_name: 'Last Christmas',
    artist_name: 'Wham!',
    album_art_url: 'https://i.scdn.co/image/ab67616d0000b273f2d7f00b0a8e83e9b7d43c36',
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    submission_order: 1,
    played: true,
    created_at: new Date().toISOString(),
    album_name: 'Last Christmas',
    release_year: 1984,
    duration_ms: 262000,
    popularity: 88,
    is_chameleon: false,
  },
  {
    id: 'sub-6',
    participant_id: 'demo-participant-3',
    track_id: 'track-6',
    track_name: 'Santa Tell Me',
    artist_name: 'Ariana Grande',
    album_art_url: 'https://i.scdn.co/image/ab67616d0000b273c3af0c2b2ff1ffc4b8d63ee1',
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    submission_order: 2,
    played: false,
    created_at: new Date().toISOString(),
    album_name: 'Santa Tell Me',
    release_year: 2014,
    duration_ms: 205000,
    popularity: 80,
    is_chameleon: false,
  },
]

// Tracks for song selection demo
export const DEMO_SEARCH_RESULTS: Track[] = [
  {
    id: 'search-1',
    name: 'Driving Home for Christmas',
    artist: 'Chris Rea',
    albumName: 'The Very Best of Chris Rea',
    albumArt: 'https://i.scdn.co/image/ab67616d0000b27378b5929b9e58e4dc11966bf3',
    releaseDate: '1986-12-01',
    releaseYear: 1986,
    durationMs: 238000,
    popularity: 76,
    explicit: false,
    previewUrl: 'https://p.scdn.co/mp3-preview/sample',
    hasPreview: true,
    isLikelyChristmas: true,
    christmasKeywordMatches: ['christmas'],
  },
  {
    id: 'search-2',
    name: 'Rockin\' Around the Christmas Tree',
    artist: 'Brenda Lee',
    albumName: 'Rockin\' Around the Christmas Tree',
    albumArt: 'https://i.scdn.co/image/ab67616d0000b273bce456da55e0765446d5f2d6',
    releaseDate: '1958-01-01',
    releaseYear: 1958,
    durationMs: 125000,
    popularity: 84,
    explicit: false,
    previewUrl: 'https://p.scdn.co/mp3-preview/sample',
    hasPreview: true,
    isLikelyChristmas: true,
    christmasKeywordMatches: ['christmas'],
  },
  {
    id: 'search-3',
    name: 'Let It Snow! Let It Snow! Let It Snow!',
    artist: 'Dean Martin',
    albumName: 'A Winter Romance',
    albumArt: 'https://i.scdn.co/image/ab67616d0000b273e85b68b8e42de48f8d9adb27',
    releaseDate: '1959-01-01',
    releaseYear: 1959,
    durationMs: 121000,
    popularity: 79,
    explicit: false,
    previewUrl: 'https://p.scdn.co/mp3-preview/sample',
    hasPreview: true,
    isLikelyChristmas: true,
    christmasKeywordMatches: ['snow'],
  },
]

// Selected tracks for submission demo
export const DEMO_SELECTED_TRACKS: Track[] = [
  {
    id: 'selected-1',
    name: 'All I Want for Christmas Is You',
    artist: 'Mariah Carey',
    albumName: 'Merry Christmas',
    albumArt: 'https://i.scdn.co/image/ab67616d0000b273073c569fdb28a8ce4cba66b2',
    releaseDate: '1994-11-01',
    releaseYear: 1994,
    durationMs: 241000,
    popularity: 85,
    explicit: false,
    previewUrl: 'https://p.scdn.co/mp3-preview/sample',
    hasPreview: true,
    isLikelyChristmas: true,
    christmasKeywordMatches: ['christmas'],
  },
  {
    id: 'selected-2',
    name: 'Last Christmas',
    artist: 'Wham!',
    albumName: 'Last Christmas',
    albumArt: 'https://i.scdn.co/image/ab67616d0000b273f2d7f00b0a8e83e9b7d43c36',
    releaseDate: '1984-12-03',
    releaseYear: 1984,
    durationMs: 262000,
    popularity: 88,
    explicit: false,
    previewUrl: 'https://p.scdn.co/mp3-preview/sample',
    hasPreview: true,
    isLikelyChristmas: true,
    christmasKeywordMatches: ['christmas'],
  },
  {
    id: 'selected-3',
    name: 'Underneath the Tree',
    artist: 'Kelly Clarkson',
    albumName: 'Wrapped in Red',
    albumArt: 'https://i.scdn.co/image/ab67616d0000b273b4c623cf3c3cc4d8e8f5f76a',
    releaseDate: '2013-10-29',
    releaseYear: 2013,
    durationMs: 227000,
    popularity: 81,
    explicit: false,
    previewUrl: 'https://p.scdn.co/mp3-preview/sample',
    hasPreview: true,
    isLikelyChristmas: true,
    christmasKeywordMatches: ['tree'],
  },
]

// Current participant for demo (viewing as Sarah - the host)
export const DEMO_CURRENT_PARTICIPANT = DEMO_PARTICIPANTS[0]

// Helper to check if demo mode is enabled
export function isDemoMode(searchParams: URLSearchParams | { get: (key: string) => string | null }): boolean {
  return searchParams.get('demo') === 'true'
}
